'use client'

import Link from 'next/link'
import { ArrowLeft, FileWarning, Loader2, Plus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { formatPlate } from '@/lib/formatters'
import { createOccurrence, listOccurrences, type Occurrence } from '@/lib/supabase/queries'

const levels = { advertencia: 'Advertência', grave: 'Grave', bloqueio: 'Bloqueio' }
export default function OcorrenciasPage() {
  const [items, setItems] = useState<Occurrence[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { listOccurrences().then(setItems).catch(() => setError('Não foi possível carregar as ocorrências.')).finally(() => setLoading(false)) }, [])
  async function add(form: FormData) { try { await createOccurrence({ rider: String(form.get('rider')), plate: String(form.get('plate')), type: String(form.get('type')), description: String(form.get('description')), level: String(form.get('level')) as Occurrence['level'] }); setItems(await listOccurrences()); setOpen(false) } catch { setError('Não foi possível registrar a ocorrência.') } }
  return <main className="min-h-screen bg-[#f7f8fa] px-5 py-6 text-slate-950 md:px-10 md:py-9"><div className="mx-auto max-w-[1180px]"><Link href="/" className="flex w-fit items-center gap-2 text-sm font-bold text-[#c92228]"><ArrowLeft size={16}/> Voltar para portaria</Link><div className="mb-7 mt-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold text-[#c92228]">Operação / Ocorrências</p><h1 className="mt-2 text-3xl font-extrabold">Ocorrências</h1><p className="mt-1 text-sm text-slate-500">Registre o fato e vincule ao entregador responsável.</p></div><button onClick={() => setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#c92228] px-4 py-3 text-sm font-bold text-white"><Plus size={17}/> Nova ocorrência</button></div>{open && <form action={add} className="mb-6 grid gap-3 rounded-2xl border border-red-100 bg-white p-5"><div className="grid gap-3 md:grid-cols-3"><input name="rider" required placeholder="Nome ou CPF do entregador" className="field"/><input name="plate" placeholder="Placa da moto" maxLength={8} className="field uppercase" onChange={(e) => { e.currentTarget.value = formatPlate(e.currentTarget.value) }}/><input name="type" required placeholder="Tipo de ocorrência" className="field"/><select name="level" className="field"><option value="advertencia">Advertência</option><option value="grave">Grave</option><option value="bloqueio">Bloqueio</option></select></div><textarea name="description" required placeholder="Descreva o que aconteceu" className="field min-h-24"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Registrar ocorrência</button></form>}{error && <p role="alert" className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="flex items-center justify-center gap-2 p-12 text-sm text-slate-500"><Loader2 className="animate-spin" size={18}/> Carregando...</div> : items.map((item) => <div key={item.id} className="flex items-start gap-4 border-b border-slate-100 p-5 last:border-0"><span className="rounded-xl bg-amber-100 p-2.5 text-amber-600"><FileWarning size={18}/></span><div className="flex-1"><p className="font-bold">{item.type}</p><p className="mt-1 text-sm text-slate-500">{item.riderName}{item.plate ? ` · ${item.plate}` : ''}</p><p className="mt-1 text-xs text-slate-400">{item.description}</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">{levels[item.level]}</span></div>)}{!loading && items.length === 0 && <p className="p-10 text-center text-sm text-slate-500">Nenhuma ocorrência registrada.</p>}</section></div></main>
}
