'use client'

import type React from 'react'
import Link from 'next/link'
import { AlertTriangle, ArrowLeft, CheckCircle2, Loader2, ShieldAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import { listAlerts, resolveAlert, type Alert } from '@/lib/supabase/queries'

export default function AlertasPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { listAlerts().then(setAlerts).catch(() => setError('Não foi possível carregar os alertas.')).finally(() => setLoading(false)) }, [])
  async function resolve(id: string) { try { await resolveAlert(id); setAlerts((current) => current.map((item) => item.id === id ? { ...item, status: 'resolvida' } : item)) } catch { setError('Não foi possível resolver o alerta.') } }
  const active = alerts.filter((item) => item.status === 'aberta')
  return <main className="min-h-screen bg-[#f7f8fa] px-5 py-6 text-slate-950 md:px-10 md:py-9"><div className="mx-auto max-w-[1000px]"><Link href="/" className="flex w-fit items-center gap-2 text-sm font-bold text-[#c92228]"><ArrowLeft size={16}/> Portaria</Link><div className="mb-8 mt-8"><p className="text-xs font-semibold text-[#c92228]">Segurança / Alertas</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Alertas de segurança</h1><p className="mt-1 text-sm text-slate-500">Acompanhe situações que exigem atenção da portaria.</p></div><section className="grid gap-4 sm:grid-cols-3"><Metric label="Alertas ativos" value={String(active.length).padStart(2, '0')} icon={<ShieldAlert/>}/><Metric label="Bloqueios" value={String(alerts.filter((item) => item.severity === 'bloqueio').length).padStart(2, '0')} icon={<AlertTriangle/>}/><Metric label="Resolvidos" value={String(alerts.filter((item) => item.status === 'resolvida').length).padStart(2, '0')} icon={<CheckCircle2/>}/></section>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-extrabold">Ocorrências que exigem atenção</h2></div>{loading ? <div className="flex items-center justify-center gap-2 p-12 text-sm text-slate-500"><Loader2 className="animate-spin" size={18}/> Carregando alertas...</div> : alerts.map((alert) => <div key={alert.id} className="flex items-start gap-4 border-b border-slate-100 p-5 last:border-0"><span className={`rounded-xl p-2.5 ${alert.severity === 'bloqueio' ? 'bg-red-100 text-red-600' : 'bg-amber-100 text-amber-600'}`}><AlertTriangle size={18}/></span><div className="flex-1"><p className="font-bold">{alert.title}</p><p className="mt-1 text-sm text-slate-500">{alert.description}</p><p className="mt-2 text-xs font-semibold text-slate-400">{new Date(alert.createdAt).toLocaleString('pt-BR')}</p></div>{alert.status === 'aberta' ? <button onClick={() => void resolve(alert.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">Resolver</button> : <span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Resolvido</span>}</div>)}{!loading && alerts.length === 0 && <p className="p-10 text-center text-sm text-slate-500">Nenhum alerta registrado.</p>}</section></div></main>
}
function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex size-9 items-center justify-center rounded-xl bg-red-50 text-[#c92228]">{icon}</div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold">{value}</p></div> }
