import Link from 'next/link'
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, BookOpen, FileWarning, ShieldAlert } from 'lucide-react'

const steps = [
  { title: 'Registrar entrada', detail: 'Selecione Entrada na Portaria, busque por nome, CPF ou placa e confirme Dar entrada.', href: '/', icon: ArrowDownToLine, tone: 'bg-red-50 text-[#c92228]' },
  { title: 'Registrar saída', detail: 'Selecione Saída, busque quem está no local e confirme Dar saída.', href: '/', icon: ArrowUpFromLine, tone: 'bg-slate-100 text-slate-700' },
  { title: 'Resolver alerta', detail: 'Abra Alertas, revise a situação e use Resolver quando a pendência estiver tratada.', href: '/alertas', icon: ShieldAlert, tone: 'bg-amber-50 text-amber-700' },
  { title: 'Registrar ocorrência', detail: 'Abra Ocorrências, descreva o fato e informe o nível de atenção necessário.', href: '/ocorrencias', icon: FileWarning, tone: 'bg-violet-50 text-violet-700' },
]

export default function ManualPage() { return <main className="min-h-screen bg-[#f7f8fa] px-4 py-5 pb-24 text-slate-950 md:px-10 md:py-8"><div className="mx-auto max-w-[900px]"><Link href="/" className="flex w-fit items-center gap-2 text-sm font-bold text-[#c92228]"><ArrowLeft size={16}/> Portaria</Link><header className="mb-5 mt-6 flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-red-50 text-[#c92228]"><BookOpen size={21}/></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#c92228]">Ajuda rápida</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight md:text-3xl">O que você precisa fazer?</h1><p className="mt-1 text-sm text-slate-500">Acesse o fluxo certo sem procurar pelo sistema.</p></div></header><section className="grid gap-3 sm:grid-cols-2">{steps.map(({ title, detail, href, icon: Icon, tone }) => <Link key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-red-200 hover:shadow-md"><div className="flex items-start gap-3"><span className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${tone}`}><Icon size={18}/></span><div className="min-w-0"><h2 className="text-sm font-extrabold group-hover:text-[#c92228]">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p><span className="mt-3 inline-block text-[11px] font-bold text-[#c92228]">Abrir fluxo →</span></div></div></Link>)}</section><section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-sm font-extrabold">Regra rápida da portaria</h2><p className="mt-2 text-xs leading-5 text-slate-500">A lista No local agora representa apenas quem entrou e ainda não teve saída registrada. Cadastros novos ficam disponíveis na busca de Entrada, mas não são contados como presentes antes do registro.</p></section></div></main> }
